name: Lint & build

on:
  push:
    branches:
      - "main"
      - "next"
    # Github Actions don't support YAML anchors yet, so we have to repeat
    # the paths-ignore in both push and pull_request events.
    # More info: https://github.com/actions/runner/issues/1182
    paths-ignore:
      - ".husky/**"
      - ".vscode/**"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - "main"
      - "next"
    paths-ignore:
      - ".husky/**"
      - ".vscode/**"
      - "LICENSE"
      - "README.md"

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yml

  build:
    name: Build
    permissions:
      contents: read
      actions: write
    needs: lint
    uses: ./.github/workflows/build.yml
