name: Lint & build & publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  lint-build-publish:
    name: Lint & build & publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - run: npm ci

      - run: npm run lint

      - name: Get version
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Bump version in package.json
        run: npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - name: Publish to Visual Studio Marketplace
        id: publishToVSMarketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OVSX_TOKEN }}

      - name: Attach release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.publishToVSMarketplace.outputs.vsixPath }}
          asset_name: digma-${{ steps.version.outputs.version }}.vsix
          tag: ${{ github.ref }}
